export const miniPage=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>xlamBOT · Telegram</title><script src="https://telegram.org/js/telegram-web-app.js"></script><style>
:root{color-scheme:dark;font:15px system-ui;background:#0d0f17;color:#eef0ff}*{box-sizing:border-box}body{margin:0}header{display:flex;align-items:center;gap:12px;padding:14px 18px;border-bottom:1px solid #343344;background:#171923;position:sticky;top:0;z-index:2}b{font-size:20px;color:#bc9eff}button,select,input{font:inherit;border:1px solid #464253;border-radius:12px;padding:11px;background:#20212e;color:#eee}button{cursor:pointer}button.primary{background:#b497f5;color:#171320;font-weight:650}button:hover{filter:brightness(1.13)}header select{max-width:190px}header .end{margin-left:auto}main{max-width:920px;margin:auto;padding:24px}section{border:1px solid #343344;border-radius:20px;background:#171923;padding:22px;margin:18px 0}p{line-height:1.6;color:#b8b6cc}.row{display:flex;gap:10px;flex-wrap:wrap}input{flex:1;min-width:200px}small{color:#a6a3bd}.badge{background:#30283f;padding:5px 9px;border-radius:8px;color:#cfb7ff}iframe{width:100%;height:calc(100dvh - 72px);border:0;display:block}pre{white-space:pre-wrap;word-break:break-word;font:13px ui-monospace,monospace;color:#dad6eb}.event{padding:16px 0;border-bottom:1px solid #35313e}.event:last-child{border:0}.severity{font-weight:700;color:#ff927f}.muted{color:#a39db6;font-size:13px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.selected{border-color:#c1a2ff;background:#352946}[hidden]{display:none!important}#notice{color:#f9c78a}h1{font-size:26px;margin:0 0 12px}h2{font-size:19px}#adminContent{min-height:150px}@media(max-width:520px){header{padding:10px;gap:6px;flex-wrap:wrap}header b{font-size:17px}header button{padding:9px;font-size:12px}header select{max-width:130px;padding:9px}header .end{margin-left:0}main{padding:14px}section{padding:17px}}
</style></head><body><header><b>xlamBOT</b><select id="pcs" aria-label="Ваш компьютер" hidden></select><button id="manage" hidden>Управление</button><button id="admin" hidden>Админ</button><button id="link" class="end" hidden>Привязать ПК</button></header><main id="intro"><section><span class="badge">TELEGRAM · MINI PANEL</span><h1 style="margin-top:16px">Твой бот под рукой</h1><p id="welcome">Открой эту панель из личных сообщений @xlambottt_bot.</p><div id="pairing" hidden><p>В веб-панели на ПК открой «Настройки → Telegram», создай ключ привязки и вставь сюда. Ключ действует 10 минут и используется один раз.</p><div class="row"><input id="key" type="password" autocomplete="off" spellcheck="false" placeholder="Ключ привязки ПК"><button id="pair" class="primary">Подключить</button></div><p class="muted">Управление доступно только твоему Telegram-аккаунту. Компьютер и xlamBOT должны оставаться включёнными. Общие настройки меняются на ПК.</p></div><p id="notice" role="status"></p></section></main><main id="adminPage" hidden><h1>Админ-панель</h1><p>Приватные технические отчёты и события. Обычные остановки и паузы не считаются ошибками. Сырые личные файлы и сообщения пользователей не собираются.</p><div class="tabs"><button data-view="errors" class="selected">Ошибки</button><button data-view="activity">Журнал</button><button data-view="versions">Версии панелей</button><select id="level" aria-label="Уровень ошибок"><option value="">Все уровни</option><option value="critical">Критические</option><option value="error">Ошибки</option><option value="warning">Предупреждения</option></select><button id="refresh">Обновить</button></div><section id="adminContent" role="status"></section><button id="older">Ранее</button></main><iframe sandbox="allow-scripts allow-forms allow-downloads allow-modals" id="panel" title="Панель вашего ПК" hidden></iframe><script>
const $=id=>document.getElementById(id),tg=window.Telegram?.WebApp;let view='errors',before='',ready=false;
new ResizeObserver(()=>{$('panel').style.height='calc(100dvh - '+document.querySelector('header').offsetHeight+'px)';}).observe(document.querySelector('header'));
const english=tg?.initDataUnsafe?.user?.language_code?.startsWith('en');
const translations={'Управление':'Control','Админ':'Admin','Привязать ПК':'Link PC','Твой бот под рукой':'Your bot at hand','Открой эту панель из личных сообщений @xlambottt_bot.':'Open this panel in @xlambottt_bot’s private chat.','Подключить':'Link PC','Админ-панель':'Admin panel','Ошибки':'Errors','Журнал':'Activity','Версии панелей':'Panel versions','Все уровни':'All levels','Критические':'Critical','Предупреждения':'Warnings','Обновить':'Refresh','Ранее':'Earlier','Загрузка…':'Loading…','Записей нет':'No records','ПК сейчас не подключён. Проверь, что xlamBOT запущен и доступ Telegram включён.':'Your PC is offline. Check that xlamBOT is running and Telegram access is enabled.','ПК привязан. Можно открыть управление или подключить ещё один компьютер.':'PC linked. Open control or link another computer.','Привяжи свой компьютер для управления ботом.':'Link your PC to control the bot.','Ключ истёк или уже использован. Создай новый на ПК.':'Key expired or already used. Create a new key on your PC.','Проверь ключ привязки.':'Check the pairing key.','Открой мини-панель из личных сообщений бота.':'Open the mini panel from the bot’s private chat.','Админ-панель недоступна.':'Admin panel unavailable.','Слишком много попыток. Подожди минуту.':'Too many attempts. Wait a minute.','Не удалось подключиться. Попробуй позже.':'Connection failed. Try again later.','В веб-панели на ПК открой «Настройки → Telegram», создай ключ привязки и вставь сюда. Ключ действует 10 минут и используется один раз.':'Open Settings → Telegram in your PC web panel. Create a pairing key and paste it here. Keys expire in 10 minutes and can be used once.','Управление доступно только твоему Telegram-аккаунту. Компьютер и xlamBOT должны оставаться включёнными. Общие настройки меняются на ПК.':'Only your Telegram account can control your linked PC. Keep the PC and xlamBOT on. Change general settings on the PC.','Приватные технические отчёты и события. Обычные остановки и паузы не считаются ошибками. Сырые личные файлы и сообщения пользователей не собираются.':'Private technical reports and activity. Normal stops and pauses are not errors. Private files and user messages are not collected.'};
const tr=value=>english?(translations[value]||value):value;
if(english){document.documentElement.lang='en';const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walk.nextNode())nodes.push(walk.currentNode);for(const node of nodes){const key=node.textContent.trim();if(translations[key])node.textContent=translations[key];}$('key').placeholder='PC pairing key';}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{credentials:'include',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(tr(({ expired_or_used_key:'Ключ истёк или уже использован. Создай новый на ПК.',invalid_key:'Проверь ключ привязки.',private_telegram_required:'Открой мини-панель из личных сообщений бота.',admin_only:'Админ-панель недоступна.',rate_limited:'Слишком много попыток. Подожди минуту.'})[d.error]||'Не удалось подключиться. Попробуй позже.'));return d;}
function screen(name){$('intro').hidden=name!=='intro';$('adminPage').hidden=name!=='admin';$('panel').hidden=name!=='panel';}
async function manage(){if(!$('pcs').value){screen('intro');return;}const base='/pc/'+$('pcs').value,grant=$('pcs').selectedOptions[0].dataset.grant;try{await api(base+'/api/devices?grant='+grant);$('panel').src=base+'/panel?grant='+grant;screen('panel');}catch(e){screen('intro');$('notice').textContent=tr('ПК сейчас не подключён. Проверь, что xlamBOT запущен и доступ Telegram включён.');}}
async function status(){const d=await api('/mini/status');$('pcs').innerHTML=d.pcs.map(p=>'<option data-grant="'+esc(p.grant)+'" value="'+esc(p.id)+'">'+esc(english?p.name.replace('ПК','PC'):p.name)+'</option>').join('');$('pcs').hidden=!d.pcs.length;$('manage').hidden=!d.pcs.length;$('link').hidden=false;$('pairing').hidden=false;$('admin').hidden=!d.admin;$('welcome').textContent=tr(d.pcs.length?'ПК привязан. Можно открыть управление или подключить ещё один компьютер.':'Привяжи свой компьютер для управления ботом.');if(d.admin&&new URLSearchParams(location.search).get('view')==='admin')admin();else if(d.pcs.length)manage();}
async function admin(){screen('admin');$('adminContent').textContent=tr('Загрузка…');try{const d=await api('/mini/admin/'+view+'?level='+$('level').value+'&before='+before);$('adminContent').innerHTML=d.rows.length?d.rows.map(r=>'<div class="event"><div><span class="severity">'+esc(r.level?.toUpperCase()||r.kind||'Панель')+'</span> · ПК '+esc(r.installation)+' · r'+esc(r.revision)+'</div><div class="muted">'+esc(new Date(r.seen*1000).toLocaleString())+'</div>'+(r.code?'<p>'+esc(r.code)+' · '+esc(r.stage)+' · '+esc(r.exception)+' · повторов: '+esc(r.count)+'</p><pre>'+esc(r.trace)+'</pre>':'')+'</div>').join(''):tr('Записей нет');$('older').hidden=d.rows.length<100;before=d.next||'';}catch(e){$('adminContent').textContent=e.message;}}
$('pair').onclick=async()=>{const button=$('pair');button.disabled=true;try{await api('/mini/pair',{key:$('key').value.trim()});$('key').value='';$('notice').textContent='';await status();}catch(e){$('notice').textContent=e.message;}finally{button.disabled=false;}};
$('link').onclick=()=>screen('intro');$('manage').onclick=manage;$('pcs').onchange=manage;$('admin').onclick=()=>{before='';admin();};$('refresh').onclick=()=>{before='';admin();};$('older').onclick=admin;$('level').onchange=()=>{before='';admin();};document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{view=button.dataset.view;before='';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b===button));$('level').hidden=view!=='errors';admin();});
(async()=>{if(!tg?.initData)return;tg.ready();tg.expand();try{await api('/mini/auth',{initData:tg.initData});ready=true;await status();}catch(e){$('notice').textContent=e.message;}})();
</script></body></html>`;
